version: 2
jobs:
  build-publish-trigger:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            set -e
            ./pipe_build_up_test.sh
      - run:
          name: Tag docker image
          command: |
            set -e
            TAG=tag-image.sh
            curl -O --fail ${CIRCLECI_SCRIPT_DIR}/${TAG}
            chmod 700 ./${TAG}
            ./${TAG}
      - run:
          name: Publish tagged docker image on dockerhub
          command: |
            set -e
            PUBLISH=publish-tagged-image.sh
            curl -O --fail ${CIRCLECI_SCRIPT_DIR}/${PUBLISH}
            chmod 700 ./${PUBLISH}
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            ./${PUBLISH}
            docker logout
      - run:
          name: Publish release tag?
          command: |
            set -e
            GIT_COMMIT_MSG=$(git log --oneline --format=%B -n 1 HEAD | head -n 1)
            if ./sh/is-release-commit.sh; then
              RELEASE=$(./sh/echo-commit-release.sh)
              docker tag cyberdojo/versioner:latest cyberdojo/versioner:${RELEASE}
              echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
              docker push cyberdojo/versioner:${RELEASE}
              docker logout
            fi

workflows:
  version: 2
  build-publish-trigger:
    jobs:
      - build-publish-trigger:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
