version: 2
jobs:
  build-publish:

    machine:
      image: ubuntu-2004:202008-01

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build docker image, test it, tag it, publish it
          command: |
            set -e
            # DOCKER_USER, DOCKER_PASS are in the context
            echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin
            ./build_test_publish.sh
            docker logout            

workflows:
  version: 2
  build-publish:
    jobs:
      - build-publish:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
